<?php

// BOOK COPY STATUS
$BOOK_COPY_STATUS = array("UnChecked" => 0,
	"Available" => 1,
	"Lent Out" => 2);

define("BOOK_COPY_STATUS_UNCHECKED",0);
define("BOOK_COPY_STATUS_AVAILABLE",1);
define("BOOK_COPY_STATUS_LENTOUT",2);

// TRANSACTION STATUS
define("TRANSACTION_STATUS_REQUESTED",1);
define("TRANSACTION_STATUS_LENT",2);
define("TRANSACTION_STATUS_RETURNED",10);

define("MESSAGE_FROM", 1);
define("MESSAGE_TO", 0);

?>